# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateField()),
                ('time_of_match', models.TimeField()),
                ('venue', models.TextField(max_length='100')),
                ('match_status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Cancelled')], default='S', max_length=1)),
                ('associated_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
            ],
        ),
    ]
