# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_match', models.DateField()),
                ('time_of_match', models.TimeField()),
                ('venue', models.TextField(max_length='100')),
                ('match_status', models.CharField(choices=[('S', 'Scheduled'), ('C', 'Cancelled')], default='S', max_length=1)),
            ],
            options={
                'ordering': ('date_of_match', 'time_of_match'),
            },
        ),
        migrations.CreateModel(
            name='PlayerMatchAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('associated_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.MatchData')),
            ],
            options={
                'ordering': ('associated_match',),
            },
        ),
    ]
