# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_and_stats', '0002_attributerating'),
        ('groups', '0002_auto_20190304_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time_of_match', models.DateTimeField()),
                ('venue', models.TextField(max_length='100')),
                ('match_status', models.CharField(choices=[('Sch', 'Scheduled'), ('Can', 'Cancelled')], default='Sch', max_length=1)),
                ('associated_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_and_stats.UserProfileData')),
            ],
        ),
    ]
