# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile_and_stats.UserProfileData'),
        ),
    ]
