# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190308_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatchavailability',
            name='associated_match',
        ),
        migrations.RemoveField(
            model_name='playermatchavailability',
            name='player',
        ),
        migrations.DeleteModel(
            name='PlayerMatchAvailability',
        ),
    ]
