# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-11 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_availabilitytable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='players',
            field=models.ManyToManyField(to='profile_and_stats.UserProfileData'),
        ),
    ]
