# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-12 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_auto_20190312_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytable',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_detail', to='profile_and_stats.UserProfileData'),
        ),
    ]
