# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_auto_20190312_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytable',
            name='matchID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matches.MatchData'),
        ),
    ]
