# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0002_auto_20190309_1352'),
        ('matches', '0012_auto_20190313_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availabilitytable',
            options={'ordering': ('matchID', 'status')},
        ),
        migrations.RemoveField(
            model_name='availabilitytable',
            name='player',
        ),
        migrations.AddField(
            model_name='availabilitytable',
            name='player',
            field=models.ManyToManyField(related_name='player_detail', to='profile_and_stats.UserProfileData'),
        ),
    ]
