# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190308_1230'),
        ('matches', '0014_auto_20190313_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitytable',
            name='availability_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='availability_group', to='groups.Group'),
            preserve_default=False,
        ),
    ]
