# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0015_availabilitytable_availability_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilitytable',
            name='availability_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_availability_group', to='groups.Group'),
        ),
    ]
