# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_auto_20190313_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchdata',
            name='selected_team',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
