# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 16:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_performancerating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancerating',
            old_name='performace_matchID',
            new_name='performance_matchID',
        ),
    ]
