# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-29 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_auto_20190329_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='selected_team',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
