# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0021_auto_20190405_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerating',
            name='performance_rated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_and_stats.UserProfileData'),
        ),
    ]
