# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-08 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0022_auto_20190408_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancerating',
            name='performance_player_rated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_player_rated', to='profile_and_stats.UserProfileData'),
        ),
    ]
