# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-09 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0024_matchdata_reminder_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchdata',
            name='players',
            field=models.ManyToManyField(null=True, related_name='linked_players', to='profile_and_stats.UserProfileData'),
        ),
    ]
