# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-11 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_and_stats', '0005_attributerating_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('subscription_length_in_days', models.DecimalField(decimal_places=0, max_digits=3)),
                ('subscribed_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_and_stats.UserProfileData')),
            ],
        ),
    ]
