# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_and_stats', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='profiles',
            field=models.ManyToManyField(to='profile_and_stats.UserProfileData'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user_id',
            field=models.ManyToManyField(to='groups.Group'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='profile_and_stats.UserProfileData'),
        ),
    ]
