# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.CharField(max_length=160),
        ),
    ]
