# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190228_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.DecimalField(decimal_places=0, max_digits=1)),
                ('user_id', models.DecimalField(decimal_places=0, max_digits=1)),
                ('admin', models.BooleanField()),
            ],
        ),
    ]
