# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190308_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='my_group', to='profile_and_stats.UserProfileData'),
        ),
    ]
