# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20190228_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmember',
            name='user_id',
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user_id',
            field=models.ManyToManyField(to='groups.Group'),
        ),
    ]
