# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('date_created',)},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'ordering': ('group_id',)},
        ),
        migrations.RenameField(
            model_name='group',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='groupmember',
            old_name='profile_id',
            new_name='profiles',
        ),
    ]
