# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile_and_stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=16)),
                ('nickname', models.CharField(blank=True, max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=14)),
                ('surname', models.CharField(blank=True, max_length=14)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('gk_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('def_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('mid_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('att_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('license_expiry_date', models.DateTimeField(default=profile_and_stats.models.one_month_hence)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
