# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import profile_and_stats.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=16)),
                ('nickname', models.CharField(blank=True, max_length=16)),
                ('first_name', models.CharField(blank=True, max_length=14)),
                ('surname', models.CharField(blank=True, max_length=14)),
                ('user_photo', models.ImageField(null=True, upload_to='images')),
                ('gk_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('def_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('mid_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('att_pref', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('license_expiry_date', models.DateTimeField(default=profile_and_stats.models.one_month_hence)),
            ],
        ),
    ]
