# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('nickname', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=14)),
                ('surname', models.CharField(max_length=14)),
                ('user_photo', models.ImageField(upload_to='images')),
                ('gk_pref', models.DecimalField(decimal_places=0, max_digits=1)),
                ('def_pref', models.DecimalField(decimal_places=0, max_digits=1)),
                ('mid_pref', models.DecimalField(decimal_places=0, max_digits=1)),
                ('att_pref', models.DecimalField(decimal_places=0, max_digits=1)),
            ],
        ),
    ]
