# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-25 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledata',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
