# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-28 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledata',
            name='user_photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
