# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gk_score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('def_score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('passing_score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('finishing_score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('movement_score', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('player_rated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_rated', to='profile_and_stats.UserProfileData')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rated_by', to='profile_and_stats.UserProfileData')),
            ],
        ),
    ]
