# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-19 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userProfile',
            new_name='UserProfileData',
        ),
    ]
