# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0002_userprofiledata_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
