# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0002_auto_20190309_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiledata',
            options={},
        ),
    ]
