# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 10:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_and_stats', '0003_auto_20190405_1032'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofiledata',
            options={'ordering': ('username',)},
        ),
    ]
